from enum import Enum

class MonsterType(str,Enum):
    AMPHIBIAN = "Amphibian"
    BIRD_WYVERN = "Bird Wyvern"
    BRUTE_WYVERN = "Brute Wyvern"
    CARAPACEONS = "Carapaceons"
    CEPHALOPODS = "Cephalopods"
    DEMI_ELDER_DRAGON = "Demi Elder Dragon"
    ELDER_DRAGON = "Elder Dragon"
    FANGED_BEAST = "Fanged Beast"
    FANGED_WYVERN = "Fanged Wyvern"
    FLYING_WYVERN = "Flying Wyvern"
    LEVIATHAN = "Leviathan"
    LYNIAN = "Lynian"
    NEOPTERON = "Neopteron"
    PISCINE_WYVERN = "Piscine Wyvern"
    RELICT = "Relict"
    SNAKE_WYVERN = "Snake Wyvern"
    TEMNOCERANT = "Temnocerant"
    UNKNOWN = "???"

class MonsterElementType(str,Enum):
    DRAGON = "Dragon"
    FIRE = "Fire"
    ICE = "Ice"
    THUNDER = "Thunder"
    WATER = "Water"

class MonsterStatusEffects(str,Enum):
    DragonBlight = "Dragonblight"
    FireBlight = "Fireblight"
    IceBlight = "Iceblight"
    ThunderBlight = "Thunderblight"
    WaterBlight = "Waterblight"

class StatusEffectWeakness(str, Enum):
    POISON = "Poison"
    SLEEP = "Sleep"
    PARALYSIS = "Paralysis"
    BLAST = "Blast"
    STUN = "Stun"
    EXAUSTION = "Exaustion"
    PARTBREAK = "Partbreak"

class MonsterStatusAliments(str, Enum):
    POISON = "Poison"
    DEADLY_POISON = "Deadly Poison"
    PARALYSIS = "Paralysis"
    SLEEP = "Sleep"
    BLASTBLIGHT = "Blastblight"
    STUN = "Stun"
    BLEEDING = "Bleeding"
    MUD = "Mud"
    SNOW = "Snow"
    EFFLUVIAL = "Effluvial"
    FRENZY = "Frenzy"
    HELLFIRE = "Hellfire"
    ROARS = "Roars"
    WIND_PRESSURE = "Wind Pressure"
    TREMORS = "Tremors"
    BUBBLE_BLIGHT = "Bubbleblight"
    WEBBED = "Webbed"
    BOUND = "Bound"
    STAMINA_THIEF = "Stamina Thief"
    ITEM_THIEF = "Item Thief"